### Setup

In [2]:
import torch
import pandas
import numpy
import matplotlib

In [3]:
print(torch.__version__)

2.1.0


In [4]:
print("Hello World!!")

Hello World!!


### Introduction

In [11]:
scalar = torch.tensor(4)

In [12]:
scalar.ndim

0

In [13]:
scalar.item()

4

In [8]:
vector = torch.tensor([2, 3])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [15]:
MATRIX = torch.tensor([[1,2],[3,4]])

In [16]:
MATRIX.ndim

2

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [27]:
MATRIX[1]

tensor([3, 4])

In [38]:
TENSOR = torch.tensor([[[1,2,3], 
                        [3,4,5], 
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])

In [34]:
TENSOR.ndim

3

In [35]:
TENSOR.shape

torch.Size([1, 3, 3])

In [43]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]])

### Random Tensors

In [56]:
random_tensor = torch.rand(3, 4, 5)
random_tensor

tensor([[[0.3560, 0.5256, 0.0115, 0.8292, 0.2396],
         [0.6687, 0.0215, 0.8323, 0.8546, 0.4027],
         [0.4446, 0.0771, 0.6086, 0.6770, 0.0509],
         [0.4891, 0.2681, 0.9227, 0.0090, 0.3992]],

        [[0.7273, 0.4375, 0.8748, 0.8587, 0.8488],
         [0.1386, 0.5082, 0.7433, 0.2975, 0.8708],
         [0.8413, 0.9668, 0.0976, 0.3898, 0.6214],
         [0.8071, 0.9278, 0.4440, 0.6477, 0.0787]],

        [[0.2628, 0.5529, 0.7587, 0.2555, 0.6987],
         [0.9408, 0.4131, 0.8757, 0.2925, 0.3431],
         [0.5477, 0.8497, 0.8109, 0.6572, 0.5775],
         [0.1390, 0.2501, 0.9861, 0.6324, 0.7938]]])

In [54]:
random_tensor.ndim

3

In [55]:
random_tensor.shape

torch.Size([3, 4, 10])

In [59]:
random_image_tensor = torch.rand(size=(3, 224, 224))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [60]:
random_image_tensor

tensor([[[0.5873, 0.9802, 0.8959,  ..., 0.9636, 0.2174, 0.8383],
         [0.8932, 0.0228, 0.2443,  ..., 0.4890, 0.5178, 0.5758],
         [0.9645, 0.9551, 0.0627,  ..., 0.5148, 0.0357, 0.0376],
         ...,
         [0.2279, 0.5512, 0.5793,  ..., 0.7331, 0.7418, 0.1832],
         [0.9191, 0.7937, 0.5704,  ..., 0.8425, 0.0042, 0.8477],
         [0.1645, 0.2745, 0.4927,  ..., 0.1830, 0.0851, 0.3123]],

        [[0.0662, 0.9137, 0.9191,  ..., 0.2401, 0.0067, 0.8449],
         [0.9890, 0.1523, 0.4684,  ..., 0.4378, 0.0302, 0.1243],
         [0.7607, 0.2775, 0.3143,  ..., 0.2461, 0.8426, 0.9423],
         ...,
         [0.5985, 0.3321, 0.2033,  ..., 0.5578, 0.9896, 0.2849],
         [0.7400, 0.1002, 0.5063,  ..., 0.4309, 0.8362, 0.6200],
         [0.2154, 0.2750, 0.5773,  ..., 0.7650, 0.6209, 0.0419]],

        [[0.9782, 0.8745, 0.5913,  ..., 0.7428, 0.3498, 0.9828],
         [0.5247, 0.4185, 0.4360,  ..., 0.9283, 0.7406, 0.9497],
         [0.1720, 0.8978, 0.9677,  ..., 0.7776, 0.1203, 0.

#### Zeros and Ones

In [62]:
zeros = torch.zeros(size=(3, 4))

In [63]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [64]:
ones = torch.ones(size=(3, 4))

In [65]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [66]:
ones.dtype

torch.float32

#### Creating a range of tensors and tensors-like

In [75]:
one_to_many = torch.arange(1, 1000, 37)

In [77]:
one_to_many

tensor([  1,  38,  75, 112, 149, 186, 223, 260, 297, 334, 371, 408, 445, 482,
        519, 556, 593, 630, 667, 704, 741, 778, 815, 852, 889, 926, 963])

In [78]:
one_to_many.shape

torch.Size([27])

In [79]:
many_numbers = torch.zeros_like(one_to_many)

In [80]:
many_numbers

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0])

### Tensor datatypes

In [81]:
float_32 = torch.rand(3,5)

In [82]:
float_32.dtype

torch.float32

In [93]:
float_16 = torch.tensor([3., 6., 9.,], dtype=torch.half, device="mps")

In [94]:
float_16.dtype

torch.float16

In [96]:
float_16_again = float_32.type(torch.half)

In [97]:
float_16_again

tensor([[0.1028, 0.6597, 0.1027, 0.9912, 0.6509],
        [0.0635, 0.4937, 0.6099, 0.0571, 0.8115],
        [0.0806, 0.0809, 0.0571, 0.5396, 0.2124]], dtype=torch.float16)

In [99]:
float_16_again * float_32

tensor([[0.0106, 0.4351, 0.0106, 0.9825, 0.4238],
        [0.0040, 0.2437, 0.3719, 0.0033, 0.6586],
        [0.0065, 0.0065, 0.0033, 0.2911, 0.0451]])

In [102]:
int_32 = torch.tensor([3,6,9], dtype=torch.long)

In [104]:
int_32.dtype

torch.int64

In [105]:
int_32

tensor([3, 6, 9])

### Getting information from tensor

In [113]:
float_16.device

device(type='mps', index=0)

In [109]:
print(float_16)

tensor([3., 6., 9.], device='mps:0', dtype=torch.float16)


In [114]:
tensor = torch.tensor([1,2,23])

In [120]:
tensor + 10

tensor([11, 12, 33])

In [121]:
tensor - 19

tensor([-18, -17,   4])

In [122]:
tensor * 10

tensor([ 10,  20, 230])

In [123]:
tensor/57

tensor([0.0175, 0.0351, 0.4035])

In [124]:
torch.mul(tensor, 10)

tensor([ 10,  20, 230])

In [125]:
torch.add(tensor, 10)

tensor([11, 12, 33])

In [126]:
torch.sub(tensor, 34)

tensor([-33, -32, -11])

In [128]:
torch.div(tensor, 56)

tensor([0.0179, 0.0357, 0.4107])

In [130]:
tensor.matmul(tensor)

tensor(534)

In [131]:
square = torch.rand(3,3)

In [134]:
torch.matmul(square, square)

tensor([[0.7585, 0.5946, 0.2990],
        [1.3175, 1.2445, 0.6239],
        [1.5174, 1.3616, 0.7951]])

In [135]:
square

tensor([[0.6169, 0.4764, 0.0248],
        [0.7555, 0.5811, 0.5704],
        [0.7230, 0.9587, 0.4799]])

In [200]:
tensor = torch.rand(size=(3, 2048,2048), dtype=torch.float32, device="mps")

In [201]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.75 ms, sys: 815 µs, total: 2.57 ms
Wall time: 1.18 ms


tensor([[[514.5256, 525.7849, 531.0200,  ..., 522.4373, 512.2709, 525.6021],
         [521.8759, 521.3867, 521.6195,  ..., 530.5706, 506.4531, 518.9810],
         [517.9263, 516.9616, 517.4608,  ..., 518.3218, 506.6769, 513.0424],
         ...,
         [511.9644, 521.7617, 529.9122,  ..., 533.3997, 512.1505, 522.1904],
         [502.2639, 518.0090, 520.4899,  ..., 517.8257, 502.7771, 515.5790],
         [510.1935, 512.8108, 516.8987,  ..., 520.1022, 504.2745, 514.2953]],

        [[489.2306, 493.3428, 505.3479,  ..., 512.3296, 511.6401, 509.1758],
         [495.9610, 499.9890, 507.5529,  ..., 521.7125, 512.8167, 513.4179],
         [494.2979, 490.9902, 497.9576,  ..., 517.0438, 512.9352, 503.9546],
         ...,
         [510.1366, 516.9266, 529.0056,  ..., 526.5761, 534.7216, 528.7946],
         [498.6093, 495.7390, 511.7073,  ..., 517.6564, 518.3395, 517.7852],
         [502.0342, 506.1115, 514.8370,  ..., 521.5438, 518.1093, 519.1119]],

        [[495.4554, 495.1933, 489.2335,  ...

In [202]:
tensor = torch.rand(size=(3, 2048,2048), dtype=torch.float32)

In [203]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 99.7 ms, sys: 14.7 ms, total: 114 ms
Wall time: 58.4 ms


tensor([[[527.3310, 526.5480, 520.0010,  ..., 523.8356, 518.7441, 520.6436],
         [523.3635, 511.8029, 521.9185,  ..., 517.7928, 512.7474, 524.3817],
         [506.4398, 510.6282, 507.0958,  ..., 505.6284, 494.4153, 510.2184],
         ...,
         [509.0320, 507.3196, 507.9975,  ..., 502.4345, 498.2432, 519.4023],
         [506.5676, 505.7324, 501.9381,  ..., 497.9286, 492.7663, 514.1630],
         [503.4186, 503.6321, 501.5042,  ..., 494.7177, 496.1634, 503.3508]],

        [[503.1441, 503.4769, 492.2256,  ..., 504.5554, 515.5139, 505.1707],
         [519.5369, 530.5468, 510.0084,  ..., 522.6744, 526.2000, 519.8041],
         [515.5078, 509.5230, 497.5610,  ..., 509.5176, 514.4039, 500.3527],
         ...,
         [521.1116, 519.0095, 499.3332,  ..., 517.0147, 518.7211, 512.9101],
         [513.6877, 514.3601, 498.3339,  ..., 515.2720, 528.9153, 513.6222],
         [510.2638, 505.9183, 500.7943,  ..., 514.5947, 518.0019, 513.2054]],

        [[525.3148, 514.3557, 525.7794,  ...

In [176]:
tensor.device

device(type='cpu')